#!/bin/bash

# Tomcat: Start/Stop Tomcat 7
#
# chkconfig: - 90 10
# description: Tomcat is a Java application Server.

. /etc/init.d/functions
#. /etc/sysconfig/network

CATALINA_HOME=/usr/local/apache-tomcat-7.0.64
TOMCAT_USER=tomcat

LOCKFILE=/var/lock/subsys/tomcat


prog=$(basename $0 | sed -e 's/^[SK][0-9][0-9]//')
pidfile=${PIDFILE-/var/run/${prog}.pid}
RETVAL=0


RETVAL=0
start(){
    echo "Starting Tomcat: "
    su - $TOMCAT_USER -c "$CATALINA_HOME/bin/startup.sh"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop(){
    echo "Shutting down Tomcat: "
    $CATALINA_HOME/bin/shutdown.sh
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;

status)
        if ! test -f ${pidfile}; then
            echo $prog is stopped
            RETVAL=3
        else
            status -p ${pidfile} $httpd
            RETVAL=$?
        fi
        ;;



#        if [ -z $(/sbin/pidof tomcat) ]; then
#            echo "Tomcat is not running..."
#        else
#            echo "Tomcat is running... pid=[$(/sbin/pidof tomcat)]"
#        fi
#        ;;

    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit $?
